[package]
name = "panic"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[profile.release]
#将panic由默认展开，切换为终止
panic = 'abort'
