    [
        'type'=>'send',
        'message'=>'RewardSystemReq',
        'msgid'=>'5026',
        'desc'=>'打开奖励系统请求'
    ],
    [
        'type'=>'rec',
        'message'=>'RewardSystemResult',
        'msgid'=>'5027',
        'desc'=>'打开奖励系统返回'
    ],
    [
        'type'=>'send',
        'message'=>'ReceiveRewardReq',
        'msgid'=>'5028',
        'desc'=>'领取奖励请求'
    ],
    [
        'type'=>'rec',
        'message'=>'ReceiveRewardResult',
        'msgid'=>'5029',
        'desc'=>'领取奖励返回'
    ]