// MFCApplication1.idl : MFCApplication1.exe 的类型库源

// 此文件将由 MIDL 编译器处理以产生
// 类型库(MFCApplication1.tlb)。

[ uuid(BD754F1C-7D68-4365-8B4E-EB871834862B), version(1.0) ]
library MFCApplication1
{
	importlib("stdole32.tlb");
	importlib("stdole2.tlb");

	//  CMFCApplication1Doc 的主调度接口
	
	[ uuid(7FA80ABE-4544-40C0-A9F2-46BF301D4CA0) ]
	dispinterface IMFCApplication1
	{
		properties:
			
		methods:
	};

	//  CMFCApplication1Doc 的类信息
	
	[ uuid(48BB0B3D-D0F3-4451-9CEA-44511B4AA8EA) ]
	coclass CMFCApplication1Doc
	{
		[default] dispinterface IMFCApplication1;
	};
};
